# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUntitled():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_untitled(self):
    # Test name: Untitled
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://chris.testingenv.org/")
    # 2 | setWindowSize | 1582x695 | 
    self.driver.set_window_size(1582, 695)
    # 3 | click | linkText=Click here to start! | 
    self.driver.find_element(By.LINK_TEXT, "Click here to start!").click()
    # 4 | click | css=.row img | 
    self.driver.find_element(By.CSS_SELECTOR, ".row img").click()
    # 5 | click | css=.bs-docs-section | 
    self.driver.find_element(By.CSS_SELECTOR, ".bs-docs-section").click()
    # 6 | click | id=loginForm:username | 
    self.driver.find_element(By.ID, "loginForm:username").click()
    # 7 | type | id=loginForm:username | johndoe
    self.driver.find_element(By.ID, "loginForm:username").send_keys("johndoe")
    # 8 | type | id=loginForm:password | test123
    self.driver.find_element(By.ID, "loginForm:password").send_keys("test123")
    # 9 | click | id=loginForm:loginButton | 
    self.driver.find_element(By.ID, "loginForm:loginButton").click()
    # 10 | click | css=body > .body | 
    self.driver.find_element(By.CSS_SELECTOR, "body > .body").click()
    # 11 | close |  | 
    self.driver.close()
  
